### ISSUE TITLE
Script error with Report Window

### ISSUE THREAD

**Issue by dietervermeulen** [ksobon/Mandrill#4] opened 2016-09-21 08:23 UTC
When running the script with the Report Window, I get a Script error (see screen shots) and at the end the window is empty.
![image](https://cloud.githubusercontent.com/assets/12096185/18703252/6a79731a-7fe5-11e6-89f9-4b1f546e2611.png)
![image](https://cloud.githubusercontent.com/assets/12096185/18703235/54bbc726-7fe5-11e6-812b-58730294200d.png)
![image](https://cloud.githubusercontent.com/assets/12096185/18703240/5911a0f2-7fe5-11e6-80ec-f2e3f0ea9df1.png)

**Comment by josols** [comment] 2016-09-21 10:37
Same with me. Win 7, dynamo 1.1 for Revit.

**Comment by ksobon** [comment] 2016-09-21 13:26
@dietervermeulen and @josols here's a link to Mandrill Primer that explains how the data needs to be structured for Parallel Coordinates Chart. 

Here's your sample re-worked to match that structure. 

![image](https://cloud.githubusercontent.com/assets/529781/18712670/76e1e70c-7fdd-11e6-8eef-9eb8bc4efadd.png)

Good luck!

**Comment by dietervermeulen** [comment] 2016-09-21 14:09
Hi Konrad,
Thanks for indicating the solution with the names. But still the scripting error remains.
![image](https://cloud.githubusercontent.com/assets/12096185/18714359/c8ede220-8015-11e6-8fd1-80f5e9a6d8a4.png)

**Comment by ksobon** [comment] 2016-09-21 14:14
can you do two things for me? 

1. check if that path that is being mentioned in the error actually points at the d3.v3.min.js file. 
2. just click yes, and then right click in the empty window and click on View Source. Can you post the source code from that window?

**Comment by dietervermeulen** [comment] 2016-09-21 14:19
1. The path exists yes.
![image](https://cloud.githubusercontent.com/assets/12096185/18714775/2bd9847e-8017-11e6-96a6-5e4aa30a01f8.png)


2. Source code: in attachment below.
[Source Code.txt](https://github.com/ksobon/Mandrill/files/485258/Source.Code.txt)

**Comment by dietervermeulen** [comment] 2016-09-21 14:19
PS: executed in Dynamo Studio 2017

**Comment by ksobon** [comment] 2016-09-21 14:24
OK, so the script looks just fine, and if the file exists I can only suggest one more thing. Please try closing Studio and firing it up in Dynamo Sandbox. That's the version that I am testing on. I did run into this issue before when firing up Mandrill from Revit, but found no solution yet. Here's a link to my conversation with Dynamo dev team: https://github.com/DynamoDS/DynamoRevit/issues/1143

**Comment by dietervermeulen** [comment] 2016-09-21 14:40
Does not work in any of the versions: Revit Dynamo, Dynamo Sandbox or Dynamo Studio (the last one is in fact now also the Dynamo Core which is the same as the Sandbox.)...

**Comment by ksobon** [comment] 2016-09-21 14:45
it seems to be working in at least one of these versions: 
![image](https://cloud.githubusercontent.com/assets/529781/18715757/690d1466-7fe8-11e6-9d17-62cd4c5d7fed.png)

I know it has an issue with running on top of Revit. I am looking at that. I don't have Studio so I can't test on that.

**Comment by dietervermeulen** [comment] 2016-09-21 14:47
Which is exactly the version I use :-)
Sorry, but not working in the Sandbox version.

**Comment by ksobon** [comment] 2016-09-21 14:51
OK, I will keep this issue open, but I am not sure how I can debug your issue without being able to re-create it. 

I am on Win7 at work and Win10 at home so operating system is probably not an issue. I guess that it has to do with what app owns the window which in turn sets the context for data. I will try looking at that if I hear from more people that they can't get it to work on their machines.

**Comment by ricardo7cordas** [comment] 2016-09-23 01:26
The same happens with me.

**Comment by ricardo7cordas** [comment] 2016-09-23 01:53
@ksobon the problem can be the path? Because the file is on the correct place.

![image](https://cloud.githubusercontent.com/assets/14896455/18771671/0c4f0416-8117-11e6-92ea-3e970796d41c.png)

![image](https://cloud.githubusercontent.com/assets/14896455/18771678/1439f9b0-8117-11e6-82c1-b6628092c0b4.png)

**Comment by ksobon** [comment] 2016-09-23 01:57
@ricardo7cordas that's not an issue. That's an error that is being thrown for every exception that happens inside of d3.js I checked that the path is fine, and it was escaped inside of code so the actual path doesn't have %20 in it but a space. Please see the TXT attached by @dietervermeulen in above comment. I have no idea what causes that error and I have very little to go on here. Sorry.

**Comment by ricardo7cordas** [comment] 2016-09-23 02:05
Ok @ksobon . Thanks for your effort

**Comment by plindjo** [comment] 2016-09-24 21:00
Hi Konrad. I am unfortunately experiencing the same issue with all charts. I've tested with sandbox and revit on win7 enterprise and win10 home, and got the script error with every setup (d3 is undefined). Since you can't recreate the issue, I thought it might be some weird reference issue or something, and figured I'd try building the package from the source. 
Unfortunately the Mandrill_d3 project will not compile since the parallelCoordinatesChart.html is missing from the repo. If you can add it, I will try to investigate further :-)
Cheers Peter

**Comment by ksobon** [comment] 2016-09-26 21:18
I think I know what the issue is. I am using a WebBrowser control to render these charts and in all its greatness its no different than using an IE7 which might or might not work on each individual person's computer depending on their own setup. Also, i found that WebBrowser control usually has trouble and unpredictable behavior when it comes to using local resources (d3.js) and it frequently denies access to these resources. I need to implement a different web browser and preferably one based on Chrome or FireFox. Currently I am looking into things like CefSharp, Awesomium and EO.WebBrowser. I will let you guys know when I have figured out which of these will fix the issue here. Thanks for the patience.

**Comment by ksobon** [comment] 2016-09-27 15:40
OK, I tested my assumption using a EO.WebBrowser which uses Chrome and it turns out that I was correct. I can get my charts working now, in Sandbox and Revit without any errors. It turns out that It was about security restrictions and how browsers disable any website javascripts from accessing local files. What is possible with the EO browser is that it allows you to disable that and access the local d3.js files.  Also it would mean consistency since it will no longer be dependent on what IE browser is installed on user computer since EO chrome browser would be distributed with Mandrill as a DLL file. 

There is one small issue though. EO charges $700 for a license. Without it, it works but will show a little window in the corner of the screen: 
![image](https://cloud.githubusercontent.com/assets/529781/18880749/fbd957f6-84a6-11e6-9a4b-bd946aab016a.png)

It's not actually embedded in the chart window, and you can move your chart to a different screen so its not a big deal, but still just slightly annoying. 

Let me know what you guys think. I will post an update with this new browser solution for you all to test. Feedback is welcome.

**Comment by plindjo** [comment] 2016-09-27 17:15
Great job! Looking forward to trying it out

**Comment by dietervermeulen** [comment] 2016-09-27 18:06
Sounds good to me too, as long as their are no legal issues with this use of the license?



Op 27 sep. 2016 om 17:40 heeft Konrad K Sobon <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


OK, I tested my assumption using a EO.WebBrowser which uses Chrome and it turns out that I was correct. I can get my charts working now, in Sandbox and Revit without any errors. It turns out that It was about security restrictions and how browsers disable any website javascripts from accessing local files. What is possible with the EO browser is that it allows you to disable that and access the local d3.js files. Also it would mean consistency since it will no longer be dependent on what IE browser is installed on user computer since EO chrome browser would be distributed with Mandrill as a DLL file.

There is one small issue though. EO charges $700 for a license. Without it, it works but will show a little window in the corner of the screen:
[image]<https://cloud.githubusercontent.com/assets/529781/18880749/fbd957f6-84a6-11e6-9a4b-bd946aab016a.png>

It's not actually embedded in the chart window, and you can move your chart to a different screen so its not a big deal, but still just slightly annoying.

Let me know what you guys think. I will post an update with this new browser solution for you all to test. Feedback is welcome.

-

**Comment by ksobon** [comment] 2016-09-27 18:09
I would rather purchase the license and then it states that its perfectly legal to ship their DLLs with the application. I am sure its OK to ship the free version as well but the pop-up is annoying. 

I need to raise some founds for this. I don't think I want to start investing $$$ and time into my Open Source projects...

**Comment by andydandy74** [comment] 2016-09-27 18:28
kickstarter

**Comment by ksobon** [comment] 2016-09-27 21:08
latest release should address issues raised here

![image](https://cloud.githubusercontent.com/assets/529781/18891835/00279a56-84d5-11e6-96b0-d6b62ef2c85c.png)

**Comment by ricardo7cordas** [comment] 2016-09-28 03:04
the error continues, even after the update.

![image](https://cloud.githubusercontent.com/assets/14896455/18899391/18792806-850f-11e6-91ff-c92918619a01.png)

![image](https://cloud.githubusercontent.com/assets/14896455/18899403/2190cdae-850f-11e6-993d-a08a1ec66aa8.png)

**Comment by ksobon** [comment] 2016-09-28 03:18
Ricardo, try the chrome window node. This one didnt change.

**Comment by ricardo7cordas** [comment] 2016-09-28 03:20
wow.. thats great.. it works!!!

![image](https://cloud.githubusercontent.com/assets/14896455/18899713/65fde2ae-8511-11e6-8d20-037f46142b3a.png)

**Comment by ksobon** [comment] 2016-09-28 03:23
Now i need to somehow solicit $700 to make the small window in bottom right corner go away. Lol. Glad it works for you.

**Closed** 2016-09-28 03:24 UTC
Labels: bug, help wanted

**Comment by ricardo7cordas** [comment] 2016-09-28 03:28
We will ask for donations. I do advertising here with the guys from Brazil if necessary. And also contribute with $$$. This is an amazing job.

**Comment by ksobon** [comment] 2016-09-28 03:32
I was thinking about starting a small fundme.com project so people can contribute. Lol. I will set something up. I need to fix a few more bugs and i will set that up. Thanks for the offer!

**Comment by ricardo7cordas** [comment] 2016-09-28 03:35
Let's do it.

**Comment by dietervermeulen** [comment] 2016-09-28 07:08
Works fine now ! Great job Konrad.

**Comment by ksobon** [comment] 2016-09-29 22:31
Here's a link to a fund if you guys want to contribute: https://funds.gofundme.com/dashboard/mandrill 

Thanks!
